yuno-payments/yuno-sdk-ios

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.1.4 Bitrise workflow
=> Bitrise - Change version number 1.1.4 

CHANGELOG.md, Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.1.7 Bitrise workflow
=> Bitrise - Change version number 1.1.7 

CHANGELOG.md, Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.1.8 Bitrise workflow
=> Bitrise - Change version number 1.1.8 

CHANGELOG.md, Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.1.9 Bitrise workflow
=> Bitrise - Change version number 1.1.9 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.1.10 Bitrise workflow
=> Bitrise - Change version number 1.1.10 

CHANGELOG.md, Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.1.11 Bitrise workflow
=> Bitrise - Change version number 1.1.11 

CHANGELOG.md, Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.1.12 Bitrise workflow
=> Bitrise - Change version number 1.1.12 

CHANGELOG.md, Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.1.13 Bitrise workflow
=> Bitrise - Change version number 1.1.13 

CHANGELOG.md, Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.1.14 Bitrise workflow
=> Bitrise - Change version number 1.1.14 

CHANGELOG.md, Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.1.15 Bitrise workflow
=> Bitrise - Change version number 1.1.15 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.1.20 Bitrise workflow
=> Bitrise - Change version number 1.1.20 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.1.22 Bitrise workflow
=> Bitrise - Change version number 1.1.22 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.1.24 Bitrise workflow
=> Bitrise - Change version number 1.1.24 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.1.26 Bitrise workflow
=> Bitrise - Change version number 1.1.26 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.1.27 Bitrise workflow
=> Bitrise - Change version number 1.1.27 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.1.28 Bitrise workflow
=> Bitrise - Change version number 1.1.28 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.1.29 Bitrise workflow
=> Bitrise - Change version number 1.1.29 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.1.31 Bitrise workflow
=> Bitrise - Change version number 1.1.31 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.1.32 Bitrise workflow
=> Bitrise - Change version number 1.1.32 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.1.34 Bitrise workflow
=> Bitrise - Change version number 1.1.34 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.2.0 Bitrise workflow
=> Bitrise - Change version number 1.2.0 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.2.1 Bitrise workflow
=> Bitrise - Change version number 1.2.1 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.2.2 Bitrise workflow
=> Bitrise - Change version number 1.2.2 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.2.3 Bitrise workflow
=> Bitrise - Change version number 1.2.3 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.2.4 Bitrise workflow
=> Bitrise - Change version number 1.2.4 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.2.5 Bitrise workflow
=> Bitrise - Change version number 1.2.5 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.2.6 Bitrise workflow
=> Bitrise - Change version number 1.2.6 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.2.7 Bitrise workflow
=> Bitrise - Change version number 1.2.7 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.6.0 Bitrise workflow
=> Bitrise - Change version number 1.6.0 

Package.swift
Change version number 1.6.1 Bitrise workflow
=> Bitrise - Change version number 1.6.1 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.6.2 Bitrise workflow
=> Bitrise - Change version number 1.6.2 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.7.0 Bitrise workflow
=> Bitrise - Change version number 1.7.0 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.8.1 Bitrise workflow
=> Bitrise - Change version number 1.8.1 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.9.0 Bitrise workflow
=> Bitrise - Change version number 1.9.0 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.10.1 Bitrise workflow
=> Bitrise - Change version number 1.10.1 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.11.0 Bitrise workflow
=> Bitrise - Change version number 1.11.0 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.12.0 Bitrise workflow
=> Bitrise - Change version number 1.12.0 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.12.1 Bitrise workflow
=> Bitrise - Change version number 1.12.1 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.12.2 Bitrise workflow
=> Bitrise - Change version number 1.12.2 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.12.3 Bitrise workflow
=> Bitrise - Change version number 1.12.3 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.13.0 Bitrise workflow
=> Bitrise - Change version number 1.13.0 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.13.1 Bitrise workflow
=> Bitrise - Change version number 1.13.1 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.14.0 Bitrise workflow
=> Bitrise - Change version number 1.14.0 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.15.0 Bitrise workflow
=> Bitrise - Change version number 1.15.0 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.16.0 Bitrise workflow
=> Bitrise - Change version number 1.16.0 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.18.0 Bitrise workflow
=> Bitrise - Change version number 1.18.0 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.19.1 Bitrise workflow
=> Bitrise - Change version number 1.19.1 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.19.2 Bitrise workflow
=> Bitrise - Change version number 1.19.2 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec, YunoWrapper/dummy.m, YunoWrapper/include/dummy.h
Change version number 1.20.0 Bitrise workflow
=> Bitrise - Change version number 1.20.0 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.21.0 Bitrise workflow
=> Bitrise - Change version number 1.21.0 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec, YunoWrapper/dummy.m, YunoWrapper/include/dummy.h
Change version number 1.21.1 Bitrise workflow
=> Bitrise - Change version number 1.21.1 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.21.2 Bitrise workflow
=> Bitrise - Change version number 1.21.2 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.22.0 Bitrise workflow
=> Bitrise - Change version number 1.22.0 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.23.0 Bitrise workflow
=> Bitrise - Change version number 1.23.0 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Reverts yuno-payments/yuno-sdk-ios#126
=> Revert "Bitrise - Change version number 1.23.0 "

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.23.1 Bitrise workflow
=> Bitrise - Change version number 1.23.1 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.23.2 Bitrise workflow
=> Bitrise - Change version number 1.23.2 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.24.0 Bitrise workflow
=> Bitrise - Change version number 1.24.0 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.24.1 Bitrise workflow
=> Bitrise - Change version number 1.24.1 

YunoSwiftUI/YunoSwiftUI/PaymentFull/PaymentFullView.swift, YunoSwiftUI/YunoSwiftUI/TransactionView/TransactionView.swift, YunoSwiftUI/YunoSwiftUI/TransactionView/TransactionViewModel.swift
This PR focuses on minor improvements to the SDK by:
- ✅ Fixing typos in documentation and code comments.
- ✅ Removing outdated code that was previously required for integrating SwiftUI with the SDK, which is now redundant.
---
1. **Typos Fixed:**  
- Corrected typos found in code comments and documentation for better clarity and understanding.
2. **Removal of Old SwiftUI Integration Code:**  
- Removed legacy code initially used for SwiftUI integration with the SDK.  
- This logic is no longer necessary, leading to a cleaner and more maintainable codebase.
---
- Built and tested the SDK to ensure there are no breaking changes.  
- Verified that SwiftUI components still work seamlessly without the removed integration logic.
---
- No functional changes introduced — this is purely cleanup …
=> Fix typos & Remove old code

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.24.2 Bitrise workflow
=> Bitrise - Change version number 1.24.2 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 1.25.0 Bitrise workflow
=> Bitrise - Change version number 1.25.0 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 2.1.0 Bitrise workflow
=> Bitrise - Change version number 2.1.0 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 2.2.0 Bitrise workflow
=> Bitrise - Change version number 2.2.0 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 2.3.0 Bitrise workflow
=> Bitrise - Change version number 2.3.0 

Example/Podfile, Package.swift, README.md, YunoSDK.podspec
Change version number 2.2.2 Bitrise workflow
=> Bitrise - Change version number 2.2.2 
